export const INDUSTRIES = [
  "Accounting & Finance",
  "Advertising & Marketing",
  "Aerospace & Defense",
  "Agriculture",
  "Architecture & Design",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Construction",
  "Consulting",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Fashion & Apparel",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare",
  "Hospitality & Tourism",
  "Human Resources",
  "Information Technology",
  "Insurance",
  "Legal",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Mining & Metals",
  "Non-Profit",
  "Pharmaceuticals",
  "Real Estate",
  "Retail & E-Commerce",
  "Telecommunications",
  "Transportation",
  "Other",
] as const;

export const EMPLOYEE_RANGES = [
  { value: "1-10", label: "1–10 employees" },
  { value: "11-50", label: "11–50 employees" },
  { value: "51-200", label: "51–200 employees" },
  { value: "201-500", label: "201–500 employees" },
  { value: "501-1000", label: "501–1000 employees" },
  { value: "1001-5000", label: "1001–5000 employees" },
  { value: "5000+", label: "5000+ employees" },
] as const;
