import type { LucideIcon } from "lucide-react";
import {
  Target,
  Search,
  Briefcase,
  GraduationCap,
  Heart,
  Clock,
  Lightbulb,
  FileText,
  BarChart3,
  PenLine,
  TrendingUp,
  BookOpen,
  Mail,
  Zap,
  AlertTriangle,
  MessageCircleQuestion,
  Scale,
  ShieldCheck,
  GitBranch,
  Users,
  DollarSign,
} from "lucide-react";

export interface CompareInsightDef {
  id: string;
  label: string;
  tab: "shared" | "jobseeker" | "business";
  icon: LucideIcon;
  iconClass: string;
}

export const COMPARE_INSIGHTS: CompareInsightDef[] = [
  {
    id: "overallScore",
    label: "Overall Match Score",
    tab: "shared",
    icon: Target,
    iconClass: "text-[#6696C9]",
  },
  {
    id: "skillsBreakdown",
    label: "Skills Breakdown",
    tab: "shared",
    icon: Search,
    iconClass: "text-orange-500",
  },
  {
    id: "experienceAlignment",
    label: "Experience Alignment",
    tab: "shared",
    icon: Briefcase,
    iconClass: "text-slate-500",
  },
  {
    id: "qualificationFit",
    label: "Qualification Fit",
    tab: "shared",
    icon: GraduationCap,
    iconClass: "text-purple-500",
  },
  {
    id: "softSkills",
    label: "Soft Skills Alignment",
    tab: "shared",
    icon: Heart,
    iconClass: "text-pink-400",
  },
  {
    id: "careerGap",
    label: "Career Gap Analysis",
    tab: "shared",
    icon: Clock,
    iconClass: "text-violet-500",
  },
  {
    id: "actionItems",
    label: "Action Items",
    tab: "jobseeker",
    icon: Lightbulb,
    iconClass: "text-amber-500",
  },
  {
    id: "atsKeywords",
    label: "ATS Keywords",
    tab: "jobseeker",
    icon: FileText,
    iconClass: "text-blue-500",
  },
  {
    id: "sectionStrength",
    label: "Section Strength",
    tab: "jobseeker",
    icon: BarChart3,
    iconClass: "text-indigo-500",
  },
  {
    id: "tailoredSummary",
    label: "Tailored Summary",
    tab: "jobseeker",
    icon: FileText,
    iconClass: "text-teal-500",
  },
  {
    id: "rewriteSuggestions",
    label: "Rewrite Suggestions",
    tab: "jobseeker",
    icon: PenLine,
    iconClass: "text-rose-500",
  },
  {
    id: "competitivePositioning",
    label: "Competitive Positioning",
    tab: "jobseeker",
    icon: TrendingUp,
    iconClass: "text-green-500",
  },
  {
    id: "industryJargon",
    label: "Industry Jargon Check",
    tab: "jobseeker",
    icon: BookOpen,
    iconClass: "text-sky-500",
  },
  {
    id: "coverLetter",
    label: "Cover Letter Starter",
    tab: "jobseeker",
    icon: Mail,
    iconClass: "text-blue-400",
  },
  {
    id: "topStrengths",
    label: "Top Strengths",
    tab: "business",
    icon: Zap,
    iconClass: "text-emerald-500",
  },
  {
    id: "riskAreas",
    label: "Risk Areas & Gaps",
    tab: "business",
    icon: AlertTriangle,
    iconClass: "text-red-400",
  },
  {
    id: "interviewFocus",
    label: "Interview Focus Points",
    tab: "business",
    icon: MessageCircleQuestion,
    iconClass: "text-violet-500",
  },
  {
    id: "overqualification",
    label: "Overqualification Assessment",
    tab: "business",
    icon: Scale,
    iconClass: "text-pink-500",
  },
  {
    id: "resumeIntegrity",
    label: "Resume Integrity Check",
    tab: "business",
    icon: ShieldCheck,
    iconClass: "text-sky-500",
  },
  {
    id: "skillTransferability",
    label: "Skill Transferability Map",
    tab: "business",
    icon: GitBranch,
    iconClass: "text-purple-500",
  },
  {
    id: "cultureCommunication",
    label: "Culture & Communication",
    tab: "business",
    icon: Users,
    iconClass: "text-teal-500",
  },
  {
    id: "salaryRange",
    label: "Salary Range Indicator",
    tab: "business",
    icon: DollarSign,
    iconClass: "text-green-500",
  },
];
